package org.optaplanner.employeerostering;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution
public class EmployeeRoster extends AbstractSolution<HardSoftScore> implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "employeeRange")
   private java.util.List<org.optaplanner.employeerostering.Employee> employeeList;
   private java.util.List<org.optaplanner.employeerostering.Shift> shiftList;
   private java.util.List<org.optaplanner.employeerostering.Skill> skillList;
   private java.util.List<org.optaplanner.employeerostering.Timeslot> timeslotList;
   @org.optaplanner.core.api.domain.solution.PlanningEntityCollectionProperty
   private java.util.List<org.optaplanner.employeerostering.ShiftAssignment> shiftAssignmentList;

   public EmployeeRoster()
   {
   }

   public java.util.List<org.optaplanner.employeerostering.Employee> getEmployeeList()
   {
      return this.employeeList;
   }

   public void setEmployeeList(
           java.util.List<org.optaplanner.employeerostering.Employee> employeeList)
   {
      this.employeeList = employeeList;
   }

   public java.util.List<org.optaplanner.employeerostering.Shift> getShiftList()
   {
      return this.shiftList;
   }

   public void setShiftList(
         java.util.List<org.optaplanner.employeerostering.Shift> shiftList)
   {
      this.shiftList = shiftList;
   }

   public java.util.List<org.optaplanner.employeerostering.Skill> getSkillList()
   {
      return this.skillList;
   }

   public void setSkillList(
         java.util.List<org.optaplanner.employeerostering.Skill> skillList)
   {
      this.skillList = skillList;
   }

   public java.util.List<org.optaplanner.employeerostering.Timeslot> getTimeslotList()
   {
      return this.timeslotList;
   }

   public void setTimeslotList(
         java.util.List<org.optaplanner.employeerostering.Timeslot> timeslotList)
   {
      this.timeslotList = timeslotList;
   }

   public java.util.List<org.optaplanner.employeerostering.ShiftAssignment> getShiftAssignmentList()
   {
      return this.shiftAssignmentList;
   }

   public void setShiftAssignmentList(
         java.util.List<org.optaplanner.employeerostering.ShiftAssignment> shiftAssignmentList)
   {
      this.shiftAssignmentList = shiftAssignmentList;
   }

   public EmployeeRoster(
         java.util.List<org.optaplanner.employeerostering.Employee> employeeList,
         java.util.List<org.optaplanner.employeerostering.Shift> shiftList,
         java.util.List<org.optaplanner.employeerostering.Skill> skillList,
         java.util.List<org.optaplanner.employeerostering.Timeslot> timeslotList,
         java.util.List<org.optaplanner.employeerostering.ShiftAssignment> shiftAssignmentList)
   {
      this.employeeList = employeeList;
      this.shiftList = shiftList;
      this.skillList = skillList;
      this.timeslotList = timeslotList;
      this.shiftAssignmentList = shiftAssignmentList;
   }

}