package org.optaplanner.employeerostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.util.List<org.optaplanner.employeerostering.Skill> skills;

   public Employee()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.List<org.optaplanner.employeerostering.Skill> getSkills()
   {
      return this.skills;
   }

   public void setSkills(
         java.util.List<org.optaplanner.employeerostering.Skill> skills)
   {
      this.skills = skills;
   }

   public Employee(java.lang.String name,
         java.util.List<org.optaplanner.employeerostering.Skill> skills)
   {
      this.name = name;
      this.skills = skills;
   }



}