package org.optaplanner.employeerostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class ShiftAssignment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private org.optaplanner.employeerostering.Shift shift;
   @org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = { "employeeRange" })
   private org.optaplanner.employeerostering.Employee employee;

   public ShiftAssignment()
   {
   }

   public org.optaplanner.employeerostering.Shift getShift()
   {
      return this.shift;
   }

   public void setShift(org.optaplanner.employeerostering.Shift shift)
   {
      this.shift = shift;
   }

   public org.optaplanner.employeerostering.Employee getEmployee()
   {
      return this.employee;
   }

   public void setEmployee(org.optaplanner.employeerostering.Employee employee)
   {
      this.employee = employee;
   }

   public ShiftAssignment(org.optaplanner.employeerostering.Shift shift,
         org.optaplanner.employeerostering.Employee employee)
   {
      this.shift = shift;
      this.employee = employee;
   }

}