package org.optaplanner.employeerostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shift implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private org.optaplanner.employeerostering.Timeslot timeslot;

   private org.optaplanner.employeerostering.Skill requiredSkill;

   public Shift()
   {
   }

   public org.optaplanner.employeerostering.Timeslot getTimeslot()
   {
      return this.timeslot;
   }

   public void setTimeslot(org.optaplanner.employeerostering.Timeslot timeslot)
   {
      this.timeslot = timeslot;
   }

   public org.optaplanner.employeerostering.Skill getRequiredSkill()
   {
      return this.requiredSkill;
   }

   public void setRequiredSkill(
         org.optaplanner.employeerostering.Skill requiredSkill)
   {
      this.requiredSkill = requiredSkill;
   }

   public Shift(org.optaplanner.employeerostering.Timeslot timeslot,
         org.optaplanner.employeerostering.Skill requiredSkill)
   {
      this.timeslot = timeslot;
      this.requiredSkill = requiredSkill;
   }

}